# Generated by Django 4.0.6 on 2022-09-22 15:34

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='formpage',
            name='_content_form',
            field=commons.models.fields.FullStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
    ]
