# Generated by Django 4.0.7 on 2022-09-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formpage_options_remove_formpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='custom_terms',
            field=models.BooleanField(default=False, help_text='Si se activa, se mostrará el mensaje personalizado que se encuentra en las configuraciones del sitio.', verbose_name='Términos y condiciones personalizados'),
        ),
    ]
