# Generated by Django 4.0.7 on 2022-09-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_formpage_custom_terms_formfield_custom_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='custom_terms',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.BooleanField(default=False, help_text='Si se activa, se mostrará el mensaje personalizado que se encuentra en las configuraciones del sitio.', verbose_name='Términos y condiciones personalizados'),
        ),
    ]
