# Generated by Django 4.0.7 on 2022-10-07 15:18

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='_content_form',
            field=commons.models.fields.DetailProductIntroStreamField(blank=True, null=True, use_json_field=None, verbose_name='Intro'),
        ),
    ]
