# Generated by Django 4.0.6 on 2022-07-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_degree_subject'),
        ('commons', '0005_delete_footermenucategories'),
    ]

    operations = [
    ]
