# Generated by Django 4.0.6 on 2022-07-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('commons', '0006_merge_20220721_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='cod_conalitep',
            field=models.CharField(default=None, max_length=255, verbose_name='Codigo CONALITEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commons.degree', verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='office_sep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Oficio SEP'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='parent_programming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Programación para Padres'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='serie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='short_description',
            field=models.TextField(default=None, verbose_name='Descripción Corta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='student_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Libro del Estudiante'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commons.subject', verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='teacher_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Libro del docente'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='teaching_dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Dosificación Docente'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video'),
        ),
    ]
