# Generated by Django 4.0.6 on 2022-07-28 21:49

import commons.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("commons", "0007_alter_subject_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailproductpage",
            old_name="degree",
            new_name="grade",
        ),
        migrations.RemoveField(
            model_name="detailproductpage",
            name="cod_conalitep",
        ),
        migrations.AddField(
            model_name="detailproductpage",
            name="cod_conaliteg",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Codigo CONALITEG"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SantillanaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_networks",
                    commons.models.fields.SocialNetworksField(
                        blank=True, default=dict, verbose_name="Redes sociales"
                    ),
                ),
                (
                    "copyright",
                    wagtail.fields.RichTextField(verbose_name="Copyright - Footer "),
                ),
                ("phone", wagtail.fields.RichTextField(verbose_name="Teléfono")),
                ("email", wagtail.fields.RichTextField(verbose_name="Email")),
                (
                    "cookies_text",
                    wagtail.fields.RichTextField(verbose_name="Texto Cookies"),
                ),
                (
                    "google_site_tag_script",
                    models.TextField(verbose_name="Global site tag (gtag.js)"),
                ),
                (
                    "google_tag_manager_script",
                    models.TextField(verbose_name="Google Tag Manager"),
                ),
                (
                    "google_tag_manager_no_script",
                    models.TextField(verbose_name="Google Tag Manager (noscript)"),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo del sitio",
                    ),
                ),
                (
                    "logo_footer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo alternativo que se utiliza en lugares de contraste oscuro, como el footer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo del footer",
                    ),
                ),
                (
                    "logo_url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="URL Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Santillana",
                "verbose_name_plural": "Configuraciones Santillana",
            },
        ),
    ]
