# Generated by Django 4.0.6 on 2022-08-24 19:48

import commons.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0019_coursedetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='date_time_event',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha y hora del evento'),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='hashtag_youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hashtag Youtube'),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='hero',
            field=commons.models.fields.HeroStreamField(blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='registration_form_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url Formulario de Inscripción'),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable'),
        ),
    ]
