# Generated by Django 4.0.6 on 2022-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0020_coursedetailpage_date_time_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='date_time_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del evento'),
        ),
    ]
