# Generated by Django 4.0.6 on 2022-08-31 19:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0020_coursedetailpage_date_time_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicHomePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commons.basepage')),
                ('_content_thematic_homepage', wagtail.fields.StreamField([], blank=True, null=True, use_json_field=None, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Thematic Home',
                'verbose_name_plural': 'Thematic Home',
            },
            bases=('commons.basepage',),
        ),
    ]
