# Generated by Django 4.0.6 on 2022-09-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0021_alter_coursedetailpage_date_time_event'),
        ('commons', '0021_thematichomepage'),
    ]

    operations = [
    ]
