# Generated by Django 4.0.6 on 2022-09-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0004_remove_svg_edit_code'),
        ('commons', '0022_merge_20220831_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='search_image_is_svg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar imagen SVG'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='search_image_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Imagen para buscadores.'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='image_is_svg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar imagen SVG'),
        ),
        migrations.AddField(
            model_name='detailproductpage',
            name='image_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Imagen del Libro'),
        ),
        migrations.AddField(
            model_name='santillanasettings',
            name='logo_footer_is_svg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar imagen SVG'),
        ),
        migrations.AddField(
            model_name='santillanasettings',
            name='logo_footer_svg',
            field=models.ForeignKey(help_text='Logo alternativo que se utiliza en lugares de contraste oscuro, como el footer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Logo del footer'),
        ),
        migrations.AddField(
            model_name='santillanasettings',
            name='logo_is_svg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar imagen SVG'),
        ),
        migrations.AddField(
            model_name='santillanasettings',
            name='logo_svg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailsvg.svg', verbose_name='Logo del sitio'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image_is_svg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar imagen SVG'),
        ),
        migrations.AddField(
            model_name='serie',
            name='image_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Imagen'),
        ),
    ]
