# Generated by Django 4.0.6 on 2022-09-14 06:17

import commons.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('commons', '0024_degree_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproductpage',
            name='title_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de la descripción'),
        ),
        migrations.AlterField(
            model_name='categoryhomepage',
            name='_content_category_homepage',
            field=commons.models.fields.CategoryHomePageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='color',
            field=models.CharField(choices=[('turquesa', 'Turquesa'), ('yellow', 'Amarillo'), ('blue', 'Azul')], default='turquesa', help_text='Personaliza la apariencia del Grado cambiando el color', max_length=255, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='detailproductpage',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Lector'),
        ),
        migrations.AlterField(
            model_name='thematichomepage',
            name='_content_thematic_homepage',
            field=commons.models.fields.ThematicHomePageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
    ]
