# Generated by Django 4.0.6 on 2022-09-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0025_detailproductpage_intro_detail_product_and_more'),
        ('commons', '0026_thankyoupage_alter_categoryhomepage_options_and_more'),
    ]

    operations = [
    ]
