# Generated by Django 4.0.6 on 2022-09-14 22:36

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0027_merge_20220914_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproductpage',
            name='intro_detail_product',
            field=commons.models.fields.DetailProductIntroStreamField(blank=True, null=True, use_json_field=None, verbose_name='Características y Beneficios'),
        ),
    ]
