# Generated by Django 4.0.6 on 2022-09-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0028_alter_detailproductpage_intro_detail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailproductpage',
            old_name='_thematic_content',
            new_name='thematic_content',
        ),
    ]
