# Generated by Django 4.0.6 on 2022-09-22 15:34

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0032_contentpage_footer_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='footer_content',
            field=commons.models.fields.ContentPageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
