# Generated by Django 4.0.6 on 2022-09-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0033_alter_contentpage_footer_content_delete_formpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThankYouPage',
        ),
    ]
