# Generated by Django 4.0.7 on 2022-09-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('commons', '0035_alter_catalogpage__content_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproductpage',
            name='scope_and_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Alcance y secuencia'),
        ),
    ]
