# Generated by Django 4.0.7 on 2022-09-30 19:59

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0036_detailproductpage_scope_and_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='hero',
            field=commons.models.fields.HeroStreamField(blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='_content_blog',
            field=commons.models.fields.BlogPageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
    ]
