# Generated by Django 4.0.7 on 2022-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0036_santillanasettings_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='santillanasettings',
            name='key_recaptcha',
            field=models.TextField(blank=True, null=True, verbose_name='Key reCAPTCHA'),
        ),
    ]
