# Generated by Django 4.0.7 on 2022-09-30 20:34

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0037_blogpage_hero_alter_blogpage__content_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailarticlepage',
            name='footer_content',
            field=commons.models.fields.CatalogPageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='detailarticlepage',
            name='_content_detail_article',
            field=commons.models.fields.DetailProductIntroStreamField(blank=True, null=True, use_json_field=None, verbose_name='Intro'),
        ),
    ]
