# Generated by Django 4.0.7 on 2022-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0038_book_alter_detailproductpage_student_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santillanasettings',
            name='secret_recaptcha',
            field=models.TextField(blank=True, null=True, verbose_name='Secret reCAPTCHA'),
        ),
    ]
