# Generated by Django 4.0.7 on 2022-10-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0038_detailarticlepage_footer_content_and_more'),
        ('commons', '0039_santillanasettings_secret_recaptcha'),
    ]

    operations = [
    ]
