# Generated by Django 4.0.7 on 2022-10-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_formfield_field_type'),
        ('commons', '0040_merge_20221003_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='santillanasettings',
            name='contact_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forms.formpage', verbose_name='Página de contacto'),
        ),
    ]
