# Generated by Django 4.0.7 on 2022-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0042_detailarticlepage_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santillanasettings',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='santillanasettings',
            name='google_site_tag_script',
        ),
        migrations.RemoveField(
            model_name='santillanasettings',
            name='google_tag_manager_no_script',
        ),
        migrations.RemoveField(
            model_name='santillanasettings',
            name='google_tag_manager_script',
        ),
    ]
