# Generated by Django 4.0.7 on 2022-10-14 15:16

import commons.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0043_remove_santillanasettings_chatbot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailarticlepage',
            name='footer_content',
            field=commons.models.fields.DetailArticlePageStreamField(blank=True, null=True, use_json_field=None, verbose_name='Contenido'),
        ),
    ]
