# Generated by Django 4.0.8 on 2022-11-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0045_remove_basepage_search_image_is_svg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='detailproductpage',
            name='editorial_team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sello Editorial'),
        ),
        migrations.AlterField(
            model_name='detailproductpage',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commons.serie', verbose_name='Serie'),
        ),
    ]
