# Generated by Django 4.0.7 on 2022-10-25 05:06
import re
import inspect
from importlib import import_module

from django.db import migrations


def remove_svg_support_on_blocks(apps, __):
    module = import_module("commons.models")
    # Recorre todos los atributos del módulo
    for attribute in module.__dict__.values():
        if inspect.isclass(attribute) and attribute.__name__.endswith("Page") and attribute.__name__ != "EmptyPage":
            Pages = getattr(module, attribute.__name__)
            for page in Pages.objects.iterator():
                for component in page.content:
                    for field in component.value:
                        if field.endswith("_old"):
                            component[re.sub("_old$", "", field)] = component[field]
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0045_remove_basepage_search_image_is_svg_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_svg_support_on_blocks, migrations.RunPython.noop)
    ]
