# Generated by Django 4.0.7 on 2022-11-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('commons', '0046_alter_serie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproductpage',
            name='new_teaching_resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Nuevos recursos didácticos'),
        ),
    ]
