# Generated by Django 4.0.6 on 2022-07-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_agflatmenuitem_footer_menu_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agflatmenuitem",
            name="footer_menu_category",
        ),
    ]
